### ISSUE TITLE
where is Init Script?

### ISSUE THREAD

**Issue by qingfeng** [JesseLeite/an-old-hope-syntax-atom#1]
`document.body.classList.add('an-old-hope-modify-ui')` add to `init.coffee` ? thanks

**Comment by jesseleite** [comment]
@qingfeng Should be "Open Your Init Script" in Atom menu, on OSX anyway :)

![init script](https://beemapp.s3-eu-west-1.amazonaws.com/8d6d7129-5a43-4741-8062-a0fe671c04e8.jpg)
