### ISSUE TITLE
Light Theme

### ISSUE THREAD

**Issue by fayesafe** [JesseLeite/an-old-hope-syntax-atom#11]
Did you ever consider releasing a light syntax theme based on the colors? I guess the contrast would be good enough if you'd 'recycle' the colors in front of a light background.

**Comment by jesseleite** [comment]
I did mess with a light theme, but it didn't feel star wars anymore.  It just felt like like a variant on base 16 light or something.  Might try again at some point :)  Thanks for your interest!
