### ISSUE TITLE
SASS variables

### ISSUE THREAD

**Issue by aldo-roman** [JesseLeite/an-old-hope-syntax-atom#12]
this theme is awesome! Now I have noticed that I can't edit SASS files as used to because variables does not get highlighted. Screenshot attached. Sass editing with the official plugin from atom:  https://atom.io/packages/language-sass

default, One Dark theme:
![screen shot 2016-02-09 at 8 55 20 am](https://cloud.githubusercontent.com/assets/497197/12918046/ecf4902c-cf0a-11e5-8208-2f3d17b2ee32.png)

An old hope theme:
![screen shot 2016-02-09 at 8 55 29 am](https://cloud.githubusercontent.com/assets/497197/12918047/ecf8c534-cf0a-11e5-9091-6ef399c90134.png)

**Comment by jesseleite** [comment]
Good call, I'll take a look at this, thanks!
