### ISSUE TITLE
CoffeeScript syntax

### ISSUE THREAD

**Issue by rricamar** [JesseLeite/an-old-hope-syntax-atom#13]
Hi there,
First , congratulations on the theme, I love the colors ,

I have a question, some JS objects in coffeescript appears without any color, is this a bug or something similar?

I use the v1.5.1 on Ubuntu 14.04

![coffe-syntax](https://cloud.githubusercontent.com/assets/8224267/12979818/ae4b9444-d0d9-11e5-98fa-330b1bcd0105.png)

**Comment by jesseleite** [comment]
Not sure it's a theme issue. Generally it's not up to the themer to add language support. We just deal with colours :) Have you tried coffeescript language support packages like [this one](https://atom.io/packages/language-coffee-script)?

**Comment by rricamar** [comment]
Hi,

A new version of atom has solved my problems, thanks for your support

**Comment by jesseleite** [comment]
Cool thanks for the update 👍
