### ISSUE TITLE
Making a version for Brackets

### ISSUE THREAD

**Issue by EspawN** [JesseLeite/an-old-hope-syntax-atom#15]
Would you consider making a branch of the theme to be used in Brackets?
I made a makeshift one myself, but there is a lot of stuff that is unknown to me, so I wouldn't know what to change it to.

**Comment by jesseleite** [comment]
Don't know much about Brackets sorry.  One day I might jump into theme porting, but won't have the time for a while, sorry!

**Comment by EspawN** [comment]
No problem! My mock version works fine as it is for my use I think. Anyways, I really love the theme so thank you very much for creating it!

**Comment by jesseleite** [comment]
And thank you for the kind words!
