### ISSUE TITLE
Deprecated selectors - Atom v1.13.0

### ISSUE THREAD

**Issue by kedwin** [JesseLeite/an-old-hope-syntax-atom#19]
Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary.

**Comment by SebastianBoyd** [comment]
Errors generated by atom:

In `an-old-hope-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
:host` => `atom-text-editor,atom-text-editor`

* `atom-text-editor .wrap-guide,
:host .wrap-guide` => `atom-text-editor .wrap-guide,atom-text-editor .wrap-guide`

* `atom-text-editor .indent-guide,
:host .indent-guide` => `atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `atom-text-editor .invisible-character,
:host .invisible-character` => `atom-text-editor .invisible-character,atom-text-editor .invisible-character`

* `atom-text-editor .gutter,
:host .gutter` => `atom-text-editor .gutter,atom-text-editor .gutter`

* `atom-text-editor .gutter .line-number.cursor-line,
:host .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line`

* `atom-text-editor .gutter .line-number.cursor-line-no-selection,
:host .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `atom-text-editor .gutter .line-number.folded,
:host .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,
:host .gutter .line-number:after,
atom-text-editor .fold-marker:after,
:host .fold-marker:after` => `atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,atom-text-editor .gutter .line-number:after,
atom-text-editor .fold-marker:after,atom-text-editor .fold-marker:after`

* `atom-text-editor .invisible,
:host .invisible` => `atom-text-editor .invisible,atom-text-editor .invisible`

* `atom-text-editor .cursor,
:host .cursor` => `atom-text-editor .cursor,atom-text-editor .cursor`

* `atom-text-editor .selection .region,
:host .selection .region` => `atom-text-editor .selection .region,atom-text-editor .selection .region`

* `atom-text-editor .search-results .marker .region,
:host .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region`

* `atom-text-editor .search-results .marker.current-result .region,
:host .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region`

* `.comment` => `.syntax--comment`

* `.entity.name.type` => `.syntax--entity.syntax--name.syntax--type`

* `.entity.other.inherited-class` => `.syntax--entity.syntax--other.syntax--inherited-class`

* `.keyword` => `.syntax--keyword`

* `.keyword.control` => `.syntax--keyword.syntax--control`

* `.keyword.operator` => `.syntax--keyword.syntax--operator`

* `.keyword.other.special-method` => `.syntax--keyword.syntax--other.syntax--special-method`

* `.keyword.other.unit` => `.syntax--keyword.syntax--other.syntax--unit`

* `.keyword.other.use` => `.syntax--keyword.syntax--other.syntax--use`

* `.keyword.other.namespace` => `.syntax--keyword.syntax--other.syntax--namespace`

* `.storage` => `.syntax--storage`

* `.storage.type` => `.syntax--storage.syntax--type`

* `.storage.type.class` => `.syntax--storage.syntax--type.syntax--class`

* `.storage.type.function` => `.syntax--storage.syntax--type.syntax--function`

* `.storage.type.var` => `.syntax--storage.syntax--type.syntax--var`

* `.storage.modifier` => `.syntax--storage.syntax--modifier`

* `.constant` => `.syntax--constant`

* `.constant.character.escape` => `.syntax--constant.syntax--character.syntax--escape`

* `.constant.numeric` => `.syntax--constant.syntax--numeric`

* `.constant.other.color` => `.syntax--constant.syntax--other.syntax--color`

* `.constant.other.symbol` => `.syntax--constant.syntax--other.syntax--symbol`

* `.variable` => `.syntax--variable`

* `.variable.interpolation` => `.syntax--variable.syntax--interpolation`

* `.variable.parameter.function` => `.syntax--variable.syntax--parameter.syntax--function`

* `.invalid.illegal` => `.syntax--invalid.syntax--illegal`

* `.string` => `.syntax--string`

* `.string.regexp` => `.syntax--string.syntax--regexp`

* `.string.regexp .source.ruby.embedded` => `.syntax--string.syntax--regexp .syntax--source.syntax--ruby.syntax--embedded`

* `.string.other.link` => `.syntax--string.syntax--other.syntax--link`

* `.punctuation.definition.comment` => `.syntax--punctuation.syntax--definition.syntax--comment`

* `.punctuation.definition.string` => `.syntax--punctuation.syntax--definition.syntax--string`

* `.punctuation.definition.variable,
.punctuation.definition.parameters,
.punctuation.definition.array` => `.syntax--punctuation.syntax--definition.syntax--variable,
.syntax--punctuation.syntax--definition.syntax--parameters,
.syntax--punctuation.syntax--definition.syntax--array`

* `.punctuation.definition.heading,
.punctuation.definition.identity` => `.syntax--punctuation.syntax--definition.syntax--heading,
.syntax--punctuation.syntax--definition.syntax--identity`

* `.punctuation.definition.bold` => `.syntax--punctuation.syntax--definition.syntax--bold`

* `.punctuation.definition.italic` => `.syntax--punctuation.syntax--definition.syntax--italic`

* `.punctuation.section.embedded` => `.syntax--punctuation.syntax--section.syntax--embedded`

* `.support.class` => `.syntax--support.syntax--class`

* `.support.function` => `.syntax--support.syntax--function`

* `.support.function.any-method` => `.syntax--support.syntax--function.syntax--any-method`

* `.entity.name.function` => `.syntax--entity.syntax--name.syntax--function`

* `.entity.name.class,
.entity.name.type.class` => `.syntax--entity.syntax--name.syntax--class,
.syntax--entity.syntax--name.syntax--type.syntax--class`

* `.entity.name.section` => `.syntax--entity.syntax--name.syntax--section`

* `.entity.name.tag` => `.syntax--entity.syntax--name.syntax--tag`

* `.entity.other.attribute-name` => `.syntax--entity.syntax--other.syntax--attribute-name`

* `.entity.other.attribute-name.id` => `.syntax--entity.syntax--other.syntax--attribute-name.syntax--id`

* `.meta.class` => `.syntax--meta.syntax--class`

* `.meta.link` => `.syntax--meta.syntax--link`

* `.meta.require` => `.syntax--meta.syntax--require`

* `.meta.selector` => `.syntax--meta.syntax--selector`

* `.meta.separator` => `.syntax--meta.syntax--separator`

* `.none` => `.syntax--none`

* `.markup.bold` => `.syntax--markup.syntax--bold`

* `.markup.changed` => `.syntax--markup.syntax--changed`

* `.markup.deleted` => `.syntax--markup.syntax--deleted`

* `.markup.italic` => `.syntax--markup.syntax--italic`

* `.markup.heading .punctuation.definition.heading` => `.syntax--markup.syntax--heading .syntax--punctuation.syntax--definition.syntax--heading`

* `.markup.inserted` => `.syntax--markup.syntax--inserted`

* `.markup.list` => `.syntax--markup.syntax--list`

* `.markup.quote` => `.syntax--markup.syntax--quote`

* `.markup.raw.inline` => `.syntax--markup.syntax--raw.syntax--inline`

* `.source.gfm .markup` => `.syntax--source.syntax--gfm .syntax--markup`

* `.source.gfm .markup.heading` => `.syntax--source.syntax--gfm .syntax--markup.syntax--heading`

* `.source.php .other.phpdoc` => `.syntax--source.syntax--php .syntax--other.syntax--phpdoc`

* `.blade.keyword,
.blade.entity,
.blade.punctuation` => `.syntax--blade.syntax--keyword,
.syntax--blade.syntax--entity,
.syntax--blade.syntax--punctuation`

* `atom-text-editor[mini] .scroll-view,
:host([mini]) .scroll-view` => `atom-text-editor[mini] .scroll-view,atom-text-editor .scroll-view`

* `.an-old-hope-modify-ui .tree-view .header.list-item,
.an-old-hope-modify-ui .tree-view .list-item` => `.an-old-hope-modify-ui .tree-view .syntax--header.list-item,
.an-old-hope-modify-ui .tree-view .list-item`

* `.an-old-hope-modify-ui .tab-bar .tab::before` => `.an-old-hope-modify-ui .tab-bar .syntax--tab::before`

* `.an-old-hope-modify-ui .tab-bar .tab .title` => `.an-old-hope-modify-ui .tab-bar .syntax--tab .syntax--title`

* `.an-old-hope-modify-ui .tab-bar .tab.active .title` => `.an-old-hope-modify-ui .tab-bar .syntax--tab.active .syntax--title`

* `.an-old-hope-modify-ui .tab-bar .tab .close-icon` => `.an-old-hope-modify-ui .tab-bar .syntax--tab .close-icon`

* `.an-old-hope-modify-ui atom-text-editor::shadow .line-number` => `.an-old-hope-modify-ui atom-text-editor.editor .line-number`

* `.an-old-hope-modify-ui a.link` => `.an-old-hope-modify-ui a.syntax--link`

* `.an-old-hope-modify-ui a.link:hover` => `.an-old-hope-modify-ui a.syntax--link:hover`

* `.an-old-hope-modify-ui .tooltip.top .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.syntax--top .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.top-left .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.top-left .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.top-right .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.top-right .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.right .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.syntax--right .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.left .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.syntax--left .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.bottom .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.syntax--bottom .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.bottom-left .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.bottom-left .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.bottom-right .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.bottom-right .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip .tooltip-inner` => `.an-old-hope-modify-ui .syntax--tooltip .tooltip-inner`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by johnroach** [comment]
👍  Really love this syntax theme. Would really appreciate it if it can be fixed.

**Comment by Superanton** [comment]
Love this theme. Hope it will get updated for Atom 1.13.

**Comment by jesseleite** [comment]
Updated theme.  Still working on UI modifications, as not all the styles seem to be taking on 1.13+
