### ISSUE TITLE
iTerm 2 color scheme

### ISSUE THREAD

**Issue by mrmurphy** [JesseLeite/an-old-hope-syntax-atom#2]
I wanted this scheme in iTerm2, so I used an online tool to make it, if you're interested:

https://terminal.sexy/#FRYZy83SAAAA6S8vdrpo6sxeQLXX9H0yI-3aq6urNDQ06S8vdrpo6sxeQLXX9H0yI-3a-fn5

That's all, and thanks!

**Comment by jesseleite** [comment]
@splodingsocks Very cool! I don't use iTerm2 myself, but looks great :)
