### ISSUE TITLE
Deprecated selector in `an-old-hope-syntax/index.less`

### ISSUE THREAD

**Issue by qws1986** [JesseLeite/an-old-hope-syntax-atom#22]
In `an-old-hope-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.an-old-hope-modify-ui .tree-view .header.list-item,
.an-old-hope-modify-ui .tree-view .list-item` => `.an-old-hope-modify-ui .tree-view .syntax--header.list-item,
.an-old-hope-modify-ui .tree-view .list-item`

* `.an-old-hope-modify-ui .tab-bar .tab::before` => `.an-old-hope-modify-ui .tab-bar .syntax--tab::before`

* `.an-old-hope-modify-ui .tab-bar .tab .title` => `.an-old-hope-modify-ui .tab-bar .syntax--tab .syntax--title`

* `.an-old-hope-modify-ui .tab-bar .tab.active .title` => `.an-old-hope-modify-ui .tab-bar .syntax--tab.active .syntax--title`

* `.an-old-hope-modify-ui .tab-bar .tab .close-icon` => `.an-old-hope-modify-ui .tab-bar .syntax--tab .close-icon`

* `.an-old-hope-modify-ui a.link` => `.an-old-hope-modify-ui a.syntax--link`

* `.an-old-hope-modify-ui a.link:hover` => `.an-old-hope-modify-ui a.syntax--link:hover`

* `.an-old-hope-modify-ui .tooltip.top .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.syntax--top .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.top-left .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.top-left .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.top-right .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.top-right .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.right .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.syntax--right .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.left .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.syntax--left .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.bottom .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.syntax--bottom .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.bottom-left .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.bottom-left .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.bottom-right .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.bottom-right .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip .tooltip-inner` => `.an-old-hope-modify-ui .syntax--tooltip .tooltip-inner`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by jesseleite** [comment]
Already pushed an update with these changes.  Gonna close this issue :P

[See full commit history](https://github.com/JesseLeite/an-old-hope-syntax-atom/commits/master)

**Comment by johnroach** [comment]
Just want to inform you that I am still getting same error. Has this change been released?

**Comment by jesseleite** [comment]
@JohnRoach With Atom 1.13 and theme version 1.0.1?  Can you also screenshot the error that you are seeing?  I ask because the errors went away for me after I upgraded the theme to 1.0.x.

**Comment by johnroach** [comment]
Hi @JesseLeite please check out these screenshots:

https://www.evernote.com/l/AOeC5ZKISfdIbI2IuxL85-arQvEjQpJEngkB/image.png

https://www.evernote.com/l/AOczBCNZRWhNpKaTHfmbOBEzYaDqrTi-mHcB/image.png

https://www.evernote.com/l/AOcdtEWayyBLMIJ3PYsnk0QBE3ngZ5-tScYB/image.png

**Comment by jesseleite** [comment]
Cool, will see what I can figure out.

**Comment by johnroach** [comment]
@JesseLeite just so you know I did a clean install for atom (needed to install it on a new system) still having same issues.

**Comment by DerekVance** [comment]
I created a pull request to fix the selectors. I no longer get the deprecation cop alert with this change.

**Comment by DerekVance** [comment]
I'm not really sure what happened but it looks like this change was implemented and then for some reason the old file was pulled back in. Your commit b6ac56e has these changes but the master branch currently shows the file in it's old state without syntax-- implemented. If you download the zip for release 1.0.1 under the releases is has the old file in it.

**Comment by jesseleite** [comment]
Hey @DerekVance, thanks for looking into this!  The reason I removed that stuff is because I didn't see `syntax--tab` etc. in the DOM when opening the inspector.  Could you explain why `syntax--tab` is needed if it's not anywhere in the DOM?

**Comment by DerekVance** [comment]
Hey @JesseLeite no problem I really dig the theme and UI integration. Check out this blog post the Atom  Dev team put out, it should shed some light as to why they made some changes. http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html

**Comment by jesseleite** [comment]
Thanks man 👍   Merged.

**Comment by DerekVance** [comment]
Thanks for merging, I appreciate it. 👍
