### ISSUE TITLE
v1.0.0 does not work with Atom 1.10

### ISSUE THREAD

**Issue by nouney** [JesseLeite/an-old-hope-syntax-atom#23]
Hi,

First, I would like to thank you for this package, it's awesome.

However the version 1.0.0 does not work with Atom 1.10: there's no syntax highlighting. I had to manually install the version 0.5.0 to get the colors back.

```
$ atom -v
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**Comment by jesseleite** [comment]
Thank you for kind words!  Yes @nouney, in Atom 1.13 there were breaking changes to DOM selectors.  I reflected this in my [package.json](https://github.com/JesseLeite/an-old-hope-syntax-atom/blob/master/package.json#L14) as a requirement.  If you are intentionally running on an older version of Atom, you'll need to run an older version of the theme as well.
