### ISSUE TITLE
Deprecated selector in `an-old-hope-syntax\index.less`

### ISSUE THREAD

**Issue by rodrigoa-ptk** [JesseLeite/an-old-hope-syntax-atom#25]
In `an-old-hope-syntax\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.an-old-hope-modify-ui .tree-view .header.list-item,
.an-old-hope-modify-ui .tree-view .list-item` => `.an-old-hope-modify-ui .tree-view .syntax--header.list-item,
.an-old-hope-modify-ui .tree-view .list-item`

* `.an-old-hope-modify-ui .tab-bar .tab::before` => `.an-old-hope-modify-ui .tab-bar .syntax--tab::before`

* `.an-old-hope-modify-ui .tab-bar .tab .title` => `.an-old-hope-modify-ui .tab-bar .syntax--tab .syntax--title`

* `.an-old-hope-modify-ui .tab-bar .tab.active .title` => `.an-old-hope-modify-ui .tab-bar .syntax--tab.active .syntax--title`

* `.an-old-hope-modify-ui .tab-bar .tab .close-icon` => `.an-old-hope-modify-ui .tab-bar .syntax--tab .close-icon`

* `.an-old-hope-modify-ui a.link` => `.an-old-hope-modify-ui a.syntax--link`

* `.an-old-hope-modify-ui a.link:hover` => `.an-old-hope-modify-ui a.syntax--link:hover`

* `.an-old-hope-modify-ui .tooltip.top .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.syntax--top .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.top-left .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.top-left .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.top-right .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.top-right .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.right .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.syntax--right .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.left .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.syntax--left .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.bottom .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.syntax--bottom .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.bottom-left .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.bottom-left .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip.bottom-right .tooltip-arrow` => `.an-old-hope-modify-ui .syntax--tooltip.bottom-right .tooltip-arrow`

* `.an-old-hope-modify-ui .tooltip .tooltip-inner` => `.an-old-hope-modify-ui .syntax--tooltip .tooltip-inner`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by jesseleite** [comment]
Resolved by #26.

**Comment by rodrigo-arias** [comment]
Good, tks!
