### ISSUE TITLE
Jade syntax colors not correct in Windows 10

### ISSUE THREAD

**Issue by RustyHoff** [JesseLeite/an-old-hope-syntax-atom#9]
I run basicly the same setup on two different machines. Recently I tried installing An Old Hope syntax on my Windows machine, and it just didn't look right. Below are screen shots of both Windows and OS X and how they look to me. 

Both are using One Dark as UI theme and An Old Hope for syntax. I'm hoping to get my Windows setup looking like my OS X.
##### On Windows 10

![Widnows 10](https://cloud.githubusercontent.com/assets/1097272/12595737/9d309cd4-c442-11e5-9805-dc1afbdcc6fa.PNG)
##### On OS X El Capitan

![OS X](https://cloud.githubusercontent.com/assets/1097272/12595809/0074278e-c443-11e5-8b67-12cdb019dd2b.png)
###### If any additional info is needed, I can supply it.

> Hokey religions and ancient weapons are no match for a good blaster at your side, kid. - Han Solo

**Comment by jesseleite** [comment]
I don't know for sure, but I think this might have to do with things like font smoothing differences between OS, which can make fonts look bolder, and more colourful.  Could also be ICC profile differing between OS as well.  I'm not sure how to address this at theme level.  That said, I'll leave this open for a bit, in case any other themers could shed light on the issue.

**Comment by plttn** [comment]
I'm jumping in here without having much of a look, but it looks to me like the syntax as shipped should be indicating something more like the W10 version, and not the OSX version. Do you have any custom user.styles going on on your Mac? 

The scope of `entity name tag jade` is being matched by `.entity.name.tag` which has the color `@vader`, which is also being applied to the `meta tag attribute class jade`. The orange look shouldn't be what's happening on a stock install of this syntax I think.

**Comment by jesseleite** [comment]
Oh whoops I didn't look close enough to see the orange there.  I thought he meant the red looked different between OSes.  Yeah, I agree.  Curious is he has any user styles or packages that could be messing with stock install.

**Comment by RustyHoff** [comment]
I prefer the OSX version, I like the different colors for classes and special characters. 
I do not have any user styles on either machine, and my packages are almost identical ( I use package sync)

**Comment by jesseleite** [comment]
Hmm that's weird.  I'll leave this issue open in case anyone else can chime in with more info.

**Comment by plttn** [comment]
@RustyHoff Would you mind zipping up the syntax theme folder from both your installs and uploading them somewhere? I'm curious to see if they're indeed the same theme to at least narrow down where it's occurring.

**Comment by RustyHoff** [comment]
@plttn are you wanting the themes package folder?

**Comment by plttn** [comment]
@RustyHoff Yeah.

**Comment by RustyHoff** [comment]
[an-old-hope-syntax_Windows.zip](https://github.com/JesseLeite/an-old-hope-syntax-atom/files/212072/an-old-hope-syntax_Windows.zip)

[an-old-hope-syntax_OSX.zip](https://github.com/JesseLeite/an-old-hope-syntax-atom/files/212077/an-old-hope-syntax_OSX.zip)

okay @plttn here you go

**Comment by plttn** [comment]
@RustyHoff Looks like the packages are identical. My guess is that you have a language package installed on OSX that isn't installed on your Windows environment.

You can do a quick check by having your text cursor be over one of the elements that's highlighted differently on OSX, and running the command palette command `Log Cursor Scope`. The list of selectors it spits out without any languages extending Jade for `&amp;` being selected is just `source.jade`, but I'm going to hazard a guess it'll be more than that on your OSX environment.

**Comment by RustyHoff** [comment]
Scopes at Coursor for my mac has 
- `source.jade`
- `tag.jade`
- `complete_tag.jade`
- `text.jade`
- `constant.character.entity.html.text.jade`

**Comment by plttn** [comment]
Looks like I've managed to tie down what's going on on your end. It's not a syntax issue.

Your OSX environment has [language-jade](https://atom.io/packages/language-jade) installed, but your Windows environment has [atom-jade](https://atom.io/packages/atom-jade) installed. They don't pass the same selectors back, so that's why you're getting different coloring. If you switch to using language-jade, it should start looking like your OSX install.

**Comment by RustyHoff** [comment]
@plttn wow. I cant believe it was something so simple. I could have sworn all my packages were identical because i was using [package-sync](https://atom.io/packages/package-sync). Thank you so much.
